pipeline {
    def app
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Build Image'){
	app=docker.build("svsaket/newjavaapp")
	}
	stage("Test Image"){
	app.inside{
	echo "app is build"}
	}
        stage("Push Image"){
	docker.WithRegistry('https://registry.hub.docker.com','Dockerapp')
	{
	app.push("latest")
	}
	echo "trying to push"
	}
    }
}
